### ISSUE TITLE
Fix triggering: incomplete image

### ISSUE THREAD

**Issue by mnissov** [ntnu-arl/blackfly_nodelet#17]
Debug incomplete image problem while trigger, verify switch has jumbo packets enabled

**Comment by nkhedekar** [comment]
The error persists on another switch which has jumbo packets enabled. The only situation in which the incomplete image is not noticed is in the case of the cameras being connected to different ports on the computer.

**Comment by nkhedekar** [comment]
Related to https://github.com/ntnu-arl/sensor_stick/issues/4

**Comment by nkhedekar** [comment]
Fixed by changing the max throughput limit. Knowledge base article added.
