### ISSUE TITLE
System timestamping

### ISSUE THREAD

**Issue by FPSychotic** [ntnu-arl/blackfly_nodelet#24]
Hi, does this node support use system timestamping, it is to can use NTP servers etc , and have the camera synched with the system without need hardware synch. 

Thanks

**Comment by nkhedekar** [comment]
The timestamp provided will be based on the system time when the device event callback occurs and the exposure duration. So if your system is synced to NTP with some other clock, you should get the correct expected timestamp subject to whatever delays you might have in getting the event callback. Off the top of my head, the delays with gigE cameras will be much smaller than with USB cameras
